version: '3.8'

services:
  # PostgreSQL Database for local development
  postgres:
    image: postgres:15-alpine
    container_name: einja-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: einja_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  postgres_data: