# Development overrides for docker-compose.yml
version: '3.8'

services:
  # Development PostgreSQL configuration
  postgres:
    environment:
      POSTGRES_DB: einja_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # Use named volume for persistence during development
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: